[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["choosak kwanraksri <btk1392545@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.112.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
